:global:
  componentName: resource-locker
  feature_goldenTests: true
  testMatrix:
    key: instance
    entries:
      - defaults
      - openshift4

docs/antora.yml:
  name: resource-locker
  title: Resource Locker Operator

.github/workflows/test.yaml:
  goldenTest_makeTarget: golden-diff -e instance=${{ matrix.instance }}
