:global:
  componentName: Resource Locker Operator
  feature_goldenTests: true
  testMatrix:
    key: instance
    entries:
      - defaults
      - lib
      - openshift4

.github/workflows/test.yaml:
  goldenTest_makeTarget: golden-diff -e instance=${{ matrix.instance }}
